package co.edu.eafit.analisisnumerico.GUI;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIPrincipal.java
 *
 * Created on 10/04/2010, 12:17:17 PM
 */



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JComponent;
import javax.swing.WindowConstants;

/**
 *
 * @author Sebastian
 */

public class GUIPrincipal extends javax.swing.JFrame {

    /** Creates new form GUIPrincipal */
    public GUIPrincipal() {
        initComponents();
        jTabbedPane1.setVisible(false);
        jLabel13.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	this.setResizable(false);
    	this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFx = new javax.swing.JTextField();
        txtFdev = new javax.swing.JTextField();
        txtG = new javax.swing.JTextField();
        txtFdd = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnGraficador = new javax.swing.JButton();
        btnMetodos = new javax.swing.JButton();
        btnAyudas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fnBusquedas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fnBiseccion = new javax.swing.JButton();
        fnReglaFalsa = new javax.swing.JButton();
        fnPuntoFijo = new javax.swing.JButton();
        fnNewton = new javax.swing.JButton();
        fnSecante = new javax.swing.JButton();
        fnRaicesMultiples = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eafit/analisisnumerico/GUI/logo2.JPG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("Análisis Númerico Solver");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("Ingreso de funciones");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("f(x)");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("g(x)");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setText("f'(x)");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setText("f''(x)");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("=");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel9.setText("=");

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel10.setText("=");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel11.setText("=");

        btnGraficador.setText("Graficador");

        btnMetodos.setText("Métodos");

        btnAyudas.setText("Ayudas");

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel13.setText("Métodos Numéricos");

        fnBusquedas.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fnBusquedas.setText("Búsquedas incrementales");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(fnBusquedas)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fnBusquedas)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Búsqueda de intervalos", jPanel2);

        fnBiseccion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fnBiseccion.setText("Bisección");

        fnReglaFalsa.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fnReglaFalsa.setText("Regla Falsa");

        fnPuntoFijo.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fnPuntoFijo.setText("Punto Fijo");

        fnNewton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fnNewton.setText("Newton");

        fnSecante.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fnSecante.setText("Secante");

        fnRaicesMultiples.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fnRaicesMultiples.setText("Raices Múltiples");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnReglaFalsa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(fnPuntoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(fnBiseccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnRaicesMultiples, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fnSecante, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(fnNewton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(343, 343, 343))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnBiseccion)
                    .addComponent(fnNewton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnReglaFalsa)
                    .addComponent(fnSecante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnPuntoFijo)
                    .addComponent(fnRaicesMultiples))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ecuaciones No Lineales", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sistemas de Ecuaciones", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, Short.MAX_VALUE)
                .addGap(199, 199, 199))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFx, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFdev, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAyudas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMetodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(btnGraficador, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(txtFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(txtFdev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGraficador)
                        .addGap(18, 18, 18)
                        .addComponent(btnMetodos)
                        .addGap(18, 18, 18)
                        .addComponent(btnAyudas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAyudas;
    private javax.swing.JButton btnGraficador;
    private javax.swing.JButton btnMetodos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton fnBiseccion;
    private javax.swing.JButton fnBusquedas;
    private javax.swing.JButton fnNewton;
    private javax.swing.JButton fnPuntoFijo;
    private javax.swing.JButton fnRaicesMultiples;
    private javax.swing.JButton fnReglaFalsa;
    private javax.swing.JButton fnSecante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtFdd;
    private javax.swing.JTextField txtFdev;
    private javax.swing.JTextField txtFx;
    private javax.swing.JTextField txtG;
    // End of variables declaration
	/**
	 * @return the btnAyudas
	 */
	public javax.swing.JButton getBtnAyudas() {
		return btnAyudas;
	}

	/**
	 * @param btnAyudas the btnAyudas to set
	 */
	public void setBtnAyudas(javax.swing.JButton btnAyudas) {
		this.btnAyudas = btnAyudas;
	}

	/**
	 * @return the btnGraficador
	 */
	public javax.swing.JButton getBtnGraficador() {
		return btnGraficador;
	}

	/**
	 * @param btnGraficador the btnGraficador to set
	 */
	public void setBtnGraficador(javax.swing.JButton btnGraficador) {
		this.btnGraficador = btnGraficador;
	}

	/**
	 * @return the btnMetodos
	 */
	public javax.swing.JButton getBtnMetodos() {
		return btnMetodos;
	}

	/**
	 * @param btnMetodos the btnMetodos to set
	 */
	public void setBtnMetodos(javax.swing.JButton btnMetodos) {
		this.btnMetodos = btnMetodos;
	}

	/**
	 * @return the buttonGroup1
	 */
	public javax.swing.ButtonGroup getButtonGroup1() {
		return buttonGroup1;
	}

	/**
	 * @param buttonGroup1 the buttonGroup1 to set
	 */
	public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
		this.buttonGroup1 = buttonGroup1;
	}

	/**
	 * @return the fnBiseccion
	 */
	public javax.swing.JButton getFnBiseccion() {
		return fnBiseccion;
	}

	/**
	 * @param fnBiseccion the fnBiseccion to set
	 */
	public void setFnBiseccion(javax.swing.JButton fnBiseccion) {
		this.fnBiseccion = fnBiseccion;
	}

	/**
	 * @return the fnBusquedas
	 */
	public javax.swing.JButton getFnBusquedas() {
		return fnBusquedas;
	}

	/**
	 * @param fnBusquedas the fnBusquedas to set
	 */
	public void setFnBusquedas(javax.swing.JButton fnBusquedas) {
		this.fnBusquedas = fnBusquedas;
	}

	/**
	 * @return the fnNewton
	 */
	public javax.swing.JButton getFnNewton() {
		return fnNewton;
	}

	/**
	 * @param fnNewton the fnNewton to set
	 */
	public void setFnNewton(javax.swing.JButton fnNewton) {
		this.fnNewton = fnNewton;
	}

	/**
	 * @return the fnPuntoFijo
	 */
	public javax.swing.JButton getFnPuntoFijo() {
		return fnPuntoFijo;
	}

	/**
	 * @param fnPuntoFijo the fnPuntoFijo to set
	 */
	public void setFnPuntoFijo(javax.swing.JButton fnPuntoFijo) {
		this.fnPuntoFijo = fnPuntoFijo;
	}

	/**
	 * @return the fnRaicesMultiples
	 */
	public javax.swing.JButton getFnRaicesMultiples() {
		return fnRaicesMultiples;
	}

	/**
	 * @param fnRaicesMultiples the fnRaicesMultiples to set
	 */
	public void setFnRaicesMultiples(javax.swing.JButton fnRaicesMultiples) {
		this.fnRaicesMultiples = fnRaicesMultiples;
	}

	/**
	 * @return the fnReglaFalsa
	 */
	public javax.swing.JButton getFnReglaFalsa() {
		return fnReglaFalsa;
	}

	/**
	 * @param fnReglaFalsa the fnReglaFalsa to set
	 */
	public void setFnReglaFalsa(javax.swing.JButton fnReglaFalsa) {
		this.fnReglaFalsa = fnReglaFalsa;
	}

	/**
	 * @return the fnSecante
	 */
	public javax.swing.JButton getFnSecante() {
		return fnSecante;
	}

	/**
	 * @param fnSecante the fnSecante to set
	 */
	public void setFnSecante(javax.swing.JButton fnSecante) {
		this.fnSecante = fnSecante;
	}

	/**
	 * @return the jPanel1
	 */
	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}

	/**
	 * @param jPanel1 the jPanel1 to set
	 */
	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	/**
	 * @return the jPanel2
	 */
	public javax.swing.JPanel getjPanel2() {
		return jPanel2;
	}

	/**
	 * @param jPanel2 the jPanel2 to set
	 */
	public void setjPanel2(javax.swing.JPanel jPanel2) {
		this.jPanel2 = jPanel2;
	}

	/**
	 * @return the jPanel3
	 */
	public javax.swing.JPanel getjPanel3() {
		return jPanel3;
	}

	/**
	 * @param jPanel3 the jPanel3 to set
	 */
	public void setjPanel3(javax.swing.JPanel jPanel3) {
		this.jPanel3 = jPanel3;
	}

	/**
	 * @return the jPanel4
	 */
	public javax.swing.JPanel getjPanel4() {
		return jPanel4;
	}

	/**
	 * @param jPanel4 the jPanel4 to set
	 */
	public void setjPanel4(javax.swing.JPanel jPanel4) {
		this.jPanel4 = jPanel4;
	}

	/**
	 * @return the jSeparator1
	 */
	public javax.swing.JSeparator getjSeparator1() {
		return jSeparator1;
	}

	/**
	 * @param jSeparator1 the jSeparator1 to set
	 */
	public void setjSeparator1(javax.swing.JSeparator jSeparator1) {
		this.jSeparator1 = jSeparator1;
	}

	/**
	 * @return the jSeparator2
	 */
	public javax.swing.JSeparator getjSeparator2() {
		return jSeparator2;
	}

	/**
	 * @param jSeparator2 the jSeparator2 to set
	 */
	public void setjSeparator2(javax.swing.JSeparator jSeparator2) {
		this.jSeparator2 = jSeparator2;
	}

	/**
	 * @return the jSeparator3
	 */
	public javax.swing.JSeparator getjSeparator3() {
		return jSeparator3;
	}

	/**
	 * @param jSeparator3 the jSeparator3 to set
	 */
	public void setjSeparator3(javax.swing.JSeparator jSeparator3) {
		this.jSeparator3 = jSeparator3;
	}

	/**
	 * @return the jTabbedPane1
	 */
	public javax.swing.JTabbedPane getjTabbedPane1() {
		return jTabbedPane1;
	}

	/**
	 * @param jTabbedPane1 the jTabbedPane1 to set
	 */
	public void setjTabbedPane1(javax.swing.JTabbedPane jTabbedPane1) {
		this.jTabbedPane1 = jTabbedPane1;
	}

	/**
	 * @return the jTextField4
	 */
	public javax.swing.JTextField getFdd() {
		return txtFdd;
	}

	/**
	 * @param jTextField4 the jTextField4 to set
	 */
	public void setFdd(javax.swing.JTextField jTextField4) {
		this.txtFdd = jTextField4;
	}

	/**
	 * @return the txtFdev
	 */
	public javax.swing.JTextField getTxtFdev() {
		return txtFdev;
	}

	/**
	 * @param txtFdev the txtFdev to set
	 */
	public void setTxtFdev(javax.swing.JTextField txtFdev) {
		this.txtFdev = txtFdev;
	}

	/**
	 * @return the txtFx
	 */
	public javax.swing.JTextField getTxtFx() {
		return txtFx;
	}

	/**
	 * @param txtFx the txtFx to set
	 */
	public void setTxtFx(javax.swing.JTextField txtFx) {
		this.txtFx = txtFx;
	}

	/**
	 * @return the txtG
	 */
	public javax.swing.JTextField getTxtG() {
		return txtG;
	}

	/**
	 * @param txtG the txtG to set
	 */
	public void setTxtG(javax.swing.JTextField txtG) {
		this.txtG = txtG;
	}

	public JComponent getjLabel13() {
		return jLabel13;
	}

    
}
