package co.edu.eafit.analisisnumerico.GUI;

import co.edu.eafit.analisisnumerico.framework.Constantes;
import co.edu.eafit.analisisnumerico.framework.GestorAyuda;

public class GUIInterpolacion extends javax.swing.JFrame {

	/** Creates new form SistemasdeEcuaciones */
	public GUIInterpolacion() {
		initComponents();
		tblValores1.setVisible(false);
        tblValores2.setVisible(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lblTamanoMatriz = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jSeparator4 = new javax.swing.JSeparator();
		jLabel1 = new javax.swing.JLabel();
		btnRegresar = new javax.swing.JButton();
		txtNumValores = new javax.swing.JTextField();
		txtValorInterpolar = new javax.swing.JTextField();
		jSeparator5 = new javax.swing.JSeparator();
		lblTamanoMatriz1 = new javax.swing.JLabel();
		btnAyuda = new javax.swing.JButton();
		lblMensajeInicial = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblValores1 = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		tblValores2 = new javax.swing.JTable();
		panel = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		btnNewton = new javax.swing.JButton();
		btnNeville = new javax.swing.JButton();
		btnLagrange = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		btnSplinesCuadratico = new javax.swing.JButton();
		btnSplinesCubico = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		lblTamanoMatriz2 = new javax.swing.JLabel();
		jSeparator6 = new javax.swing.JSeparator();
		txtFuncion = new javax.swing.JTextField();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jsalir1 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		InfoGeneral = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jDiferencias = new javax.swing.JMenuItem();
		jNeville = new javax.swing.JMenuItem();
		jPolinomio = new javax.swing.JMenuItem();
		jSplines = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblTamanoMatriz.setText("Número de valores iniciales:");

		jLabel2.setFont(new java.awt.Font("Georgia", 3, 18));
		jLabel2.setText("Análisis Númerico Solver");

		jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Constantes.RUTAIMAGEN))); // NOI18N

		btnRegresar.setText("Regresar");
		btnRegresar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRegresarActionPerformed(evt);
			}
		});

		lblTamanoMatriz1.setText("Valor a interpolar:");

		btnAyuda.setText("Ayuda");
		btnAyuda.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAyudaActionPerformed(evt);
			}
		});

		lblMensajeInicial.setText("Ingrese por favor el número de valores iniciales");

		tblValores1.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null}
				},
				new String [] {
						"x", "f(x) (Opcional)"
				}
		));
		jScrollPane2.setViewportView(tblValores1);

		tblValores2.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null},
						{null, null}
				},
				new String [] {
						"x", "f(x) (Opcional)"
				}
		));
		jScrollPane3.setViewportView(tblValores2);

		btnNewton.setFont(new java.awt.Font("Georgia", 0, 11));
		btnNewton.setText("Diferencias Divididas -Newton");

		btnNeville.setFont(new java.awt.Font("Georgia", 0, 11));
		btnNeville.setText("Neville");
		btnNeville.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNevilleActionPerformed(evt);
			}
		});

		btnLagrange.setFont(new java.awt.Font("Georgia", 0, 11));
		btnLagrange.setText("Polinomio Interpolante Lagrange");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(btnNeville, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnNewton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnLagrange, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
								.addContainerGap(131, Short.MAX_VALUE))
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(btnNewton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnNeville)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnLagrange)
						.addContainerGap(50, Short.MAX_VALUE))
		);

		panel.addTab("Interpolacion", jPanel2);

		btnSplinesCuadratico.setText("Splines  Cuadratico");
		btnSplinesCuadratico.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSplinesCuadraticoActionPerformed(evt);
			}
		});

		btnSplinesCubico.setText("Splines  Cubico");
		btnSplinesCubico.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSplinesCubicoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(btnSplinesCuadratico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(228, Short.MAX_VALUE))
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(btnSplinesCubico, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
												.addGap(228, 228, 228))))
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(21, 21, 21)
						.addComponent(btnSplinesCuadratico)
						.addGap(18, 18, 18)
						.addComponent(btnSplinesCubico)
						.addContainerGap(57, Short.MAX_VALUE))
		);

		panel.addTab("Splines", jPanel1);

		jLabel13.setFont(new java.awt.Font("Georgia", 0, 14));
		jLabel13.setText("Métodos Numéricos");

		lblTamanoMatriz2.setText("    Función:");

		jMenu1.setText("Archivo");

		jsalir1.setText("Salir");
		jsalir1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jsalir1ActionPerformed(evt);
			}
		});
		jMenu1.add(jsalir1);

		jMenuBar1.add(jMenu1);

		jMenu3.setText("Acerca de");
		jMenu3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenu3ActionPerformed(evt);
			}
		});

		InfoGeneral.setText("Información General ");
		InfoGeneral.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				InfoGeneralActionPerformed(evt);
			}
		});
		jMenu3.add(InfoGeneral);

		jMenuBar1.add(jMenu3);

		jMenu2.setText("Ayudas");

		jDiferencias.setText("Diferencias Divididas");
		jDiferencias.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jDiferenciasActionPerformed(evt);
			}
		});
		jMenu2.add(jDiferencias);

		jNeville.setText("Neville");
		jNeville.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jNevilleActionPerformed(evt);
			}
		});
		jMenu2.add(jNeville);

		jPolinomio.setText("Polinomio Interpolante Lagrange");
		jPolinomio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPolinomioActionPerformed(evt);
			}
		});
		jMenu2.add(jPolinomio);

		jSplines.setText("Splines");
		jSplines.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jSplinesActionPerformed(evt);
			}
		});
		jMenu2.add(jSplines);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblTamanoMatriz)
												.addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(layout.createSequentialGroup()
														.addGap(28, 28, 28)
														.addComponent(txtValorInterpolar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addGap(28, 28, 28)
																.addComponent(txtNumValores, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(layout.createSequentialGroup()
																		.addGap(19, 19, 19)
																		.addComponent(lblTamanoMatriz1))
																		.addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout.createSequentialGroup()
																				.addGap(28, 28, 28)
																				.addComponent(lblTamanoMatriz2))
																				.addGroup(layout.createSequentialGroup()
																						.addGap(8, 8, 8)
																						.addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(jLabel2)
																								.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addGroup(layout.createSequentialGroup()
																										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(layout.createSequentialGroup()
																														.addComponent(lblMensajeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGap(63, 63, 63))
																														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																																.addGap(8, 8, 8)
																																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																																		.addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
																																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addGroup(layout.createSequentialGroup()
																																						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
																																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																						.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
																																						.addGap(114, 114, 114)))
																																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																								.addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
																																								.addComponent(btnAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
																																								.addGap(29, 29, 29)
																																								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																										.addComponent(jLabel1)
																																										.addGroup(layout.createSequentialGroup()
																																												.addGap(56, 56, 56)
																																												.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																																												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup()
														.addGap(17, 17, 17)
														.addComponent(jLabel1)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(btnAyuda)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(btnRegresar))
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(jLabel2)
																						.addGap(28, 28, 28)
																						.addComponent(lblMensajeInicial)
																						.addGap(18, 18, 18)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																								.addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
																								.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
																								.addGap(30, 30, 30)
																								.addComponent(jLabel13)))
																								.addGap(18, 18, 18)
																								.addComponent(panel, 0, 0, Short.MAX_VALUE))))
																								.addGroup(layout.createSequentialGroup()
																										.addGap(47, 47, 47)
																										.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(110, 110, 110)
																										.addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18, 18, 18)
																										.addComponent(lblTamanoMatriz)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(txtNumValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(14, 14, 14)
																										.addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(lblTamanoMatriz1)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(txtValorInterpolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(14, 14, 14)
																										.addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(lblTamanoMatriz2)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(14, 14, 14)
																										.addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addContainerGap(23, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>

	private void btnNevilleActionPerformed(java.awt.event.ActionEvent evt) {                                           
		// TODO add your handling code here:
	}                                          

	private void jDiferenciasActionPerformed(java.awt.event.ActionEvent evt) {                                             
		GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.NEWTONDIFERENCIASDIVIDIDAS);
	}                                            

	private void jNevilleActionPerformed(java.awt.event.ActionEvent evt) {                                         
		GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.NEVILLE);
	}                                        

	private void jPolinomioActionPerformed(java.awt.event.ActionEvent evt) {                                           
		GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.LAGRANGE);
	}                                          

	private void InfoGeneralActionPerformed(java.awt.event.ActionEvent evt) {                                            
		GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.INFOGENERAL);
	}                                           

	private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
		// TODO add your handling code here:
	}                                      

	private void jsalir1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
		System.exit(0);
	}                                       

	private void btnSplinesCuadraticoActionPerformed(java.awt.event.ActionEvent evt) {                                                     
		// TODO add your handling code here:
	}                                                    

	private void btnSplinesCubicoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
		// TODO add your handling code here:
	}                                                

	private void jSplinesActionPerformed(java.awt.event.ActionEvent evt) {                                         
		GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.SPLINES);
	}                                        

	private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
	}                                        

	private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here:
	}                                           

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUIInterpolacion().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	public javax.swing.JMenuItem InfoGeneral;
	public javax.swing.JButton btnAyuda;
	public javax.swing.JButton btnLagrange;
	public javax.swing.JButton btnNeville;
	public javax.swing.JButton btnNewton;
	public javax.swing.JButton btnRegresar;
	public javax.swing.JButton btnSplinesCuadratico;
	public javax.swing.JButton btnSplinesCubico;
	public javax.swing.JMenuItem jDiferencias;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabel13;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JMenu jMenu1;
	public javax.swing.JMenu jMenu2;
	public javax.swing.JMenu jMenu3;
	public javax.swing.JMenuBar jMenuBar1;
	public javax.swing.JMenuItem jNeville;
	public javax.swing.JPanel jPanel1;
	public javax.swing.JPanel jPanel2;
	public javax.swing.JMenuItem jPolinomio;
	public javax.swing.JScrollPane jScrollPane2;
	public javax.swing.JScrollPane jScrollPane3;
	public javax.swing.JSeparator jSeparator1;
	public javax.swing.JSeparator jSeparator2;
	public javax.swing.JSeparator jSeparator3;
	public javax.swing.JSeparator jSeparator4;
	public javax.swing.JSeparator jSeparator5;
	public javax.swing.JSeparator jSeparator6;
	public javax.swing.JMenuItem jSplines;
	public javax.swing.JMenuItem jsalir1;
	public javax.swing.JLabel lblMensajeInicial;
	public javax.swing.JLabel lblTamanoMatriz;
	public javax.swing.JLabel lblTamanoMatriz1;
	public javax.swing.JLabel lblTamanoMatriz2;
	public javax.swing.JTabbedPane panel;
	public javax.swing.JTable tblValores1;
	public javax.swing.JTable tblValores2;
	public javax.swing.JTextField txtFuncion;
	public javax.swing.JTextField txtNumValores;
	public javax.swing.JTextField txtValorInterpolar;
	// End of variables declaration

}
