package co.edu.eafit.analisisnumerico.GUI;

import co.edu.eafit.analisisnumerico.framework.Constantes;
import co.edu.eafit.analisisnumerico.framework.GestorAyuda;



/**
 *
 * @author nico
 */
public class GUIIntegracion extends javax.swing.JFrame {

    /** Creates new form GuiIntegracion */
    public GUIIntegracion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblTamanoMatriz1 = new javax.swing.JLabel();
        lblTamanoMatriz2 = new javax.swing.JLabel();
        lblTamanoMatriz3 = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        txtLimiteInferior = new javax.swing.JTextField();
        txtLimiteSuperior = new javax.swing.JTextField();
        lblTamanoMatriz4 = new javax.swing.JLabel();
        txtDelta = new javax.swing.JTextField();
        panel3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        btnTrapecioSencillo = new javax.swing.JButton();
        btnTrapecioGeneralizado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSimpsonuntercio = new javax.swing.JButton();
        btnSimpsonuntercioGeneralizado = new javax.swing.JButton();
        btnSimpsonTresOctavos = new javax.swing.JButton();
        lblTamanoMatriz5 = new javax.swing.JLabel();
        txtParticiones = new javax.swing.JTextField();
        btnAyuda = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jsalir1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        InfoGeneral = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jTrapecio = new javax.swing.JMenuItem();
        jSimpson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Constantes.RUTAIMAGEN))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("Análisis Númerico Solver");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblTamanoMatriz1.setText("Funcion F(x):");

        lblTamanoMatriz2.setText("Limite Inferior (a):");

        lblTamanoMatriz3.setText("Limite Superior (b):");

        txtFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionActionPerformed(evt);
            }
        });

        txtLimiteInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteInferiorActionPerformed(evt);
            }
        });

        txtLimiteSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteSuperiorActionPerformed(evt);
            }
        });

        lblTamanoMatriz4.setText("Delta (h):");

        txtDelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeltaActionPerformed(evt);
            }
        });

        btnTrapecioSencillo.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnTrapecioSencillo.setText("Trapecio Sencillo");
        btnTrapecioSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrapecioSencilloActionPerformed(evt);
            }
        });

        btnTrapecioGeneralizado.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnTrapecioGeneralizado.setText("Trapecio Generalizado");
        btnTrapecioGeneralizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrapecioGeneralizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrapecioSencillo)
                .addGap(18, 18, 18)
                .addComponent(btnTrapecioGeneralizado)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrapecioSencillo)
                    .addComponent(btnTrapecioGeneralizado))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        panel3.addTab("Integracion Trapecio", jPanel5);

        btnSimpsonuntercio.setText("Simpson 1/3");
        btnSimpsonuntercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpsonuntercioActionPerformed(evt);
            }
        });

        btnSimpsonuntercioGeneralizado.setText("Simpson  1/3 Generalizado");
        btnSimpsonuntercioGeneralizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpsonuntercioGeneralizadoActionPerformed(evt);
            }
        });

        btnSimpsonTresOctavos.setText("Simpson 3/8");
        btnSimpsonTresOctavos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpsonTresOctavosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpsonuntercio)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpsonuntercioGeneralizado))
                    .addComponent(btnSimpsonTresOctavos))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpsonuntercioGeneralizado)
                    .addComponent(btnSimpsonuntercio))
                .addGap(18, 18, 18)
                .addComponent(btnSimpsonTresOctavos)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panel3.addTab("Integracion Simpson", jPanel1);

        lblTamanoMatriz5.setText("Particiones(n):");

        txtParticiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParticionesActionPerformed(evt);
            }
        });

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado");

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel13.setText("Métodos Numéricos");

        jMenu1.setText("Archivo");

        jsalir1.setText("Salir");
        jsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalir1ActionPerformed(evt);
            }
        });
        jMenu1.add(jsalir1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Acerca de");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        InfoGeneral.setText("Información General ");
        InfoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoGeneralActionPerformed(evt);
            }
        });
        jMenu3.add(InfoGeneral);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayudas");

        jTrapecio.setText("Trapecio");
        jTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrapecioActionPerformed(evt);
            }
        });
        jMenu2.add(jTrapecio);

        jSimpson.setText("Simpson");
        jSimpson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpsonActionPerformed(evt);
            }
        });
        jMenu2.add(jSimpson);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTamanoMatriz3)
                                .addComponent(lblTamanoMatriz2)
                                .addComponent(lblTamanoMatriz1)
                                .addComponent(lblTamanoMatriz4)
                                .addComponent(lblTamanoMatriz5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtParticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtLimiteInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLimiteSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDelta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(440, 440, 440)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTamanoMatriz1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLimiteInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTamanoMatriz2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLimiteSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTamanoMatriz3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTamanoMatriz4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtParticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTamanoMatriz5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnAyuda)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)))
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addGap(11, 11, 11)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(103, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(54, 54, 54)))
        );

        pack();
    }// </editor-fold>

    private void jsalir1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	System.exit(0);
}                                       

    private void InfoGeneralActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.INFOGENERAL);
}                                           

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
}                                      

    private void jTrapecioActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.TRAPECIO);
}                                         

    private void jSimpsonActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.SIMPSON);
}                                        

    private void txtFuncionActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
}                                          

    private void txtLimiteInferiorActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
}                                        

    private void txtLimiteSuperiorActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
}                                        

    private void txtDeltaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnTrapecioGeneralizadoActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
}                                                       

    private void txtParticionesActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnTrapecioSencilloActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void btnSimpsonuntercioActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void btnSimpsonuntercioGeneralizadoActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void btnSimpsonTresOctavosActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIIntegracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    public javax.swing.JMenuItem InfoGeneral;
    public javax.swing.JButton btnAyuda;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnSimpsonTresOctavos;
    public javax.swing.JButton btnSimpsonuntercio;
    public javax.swing.JButton btnSimpsonuntercioGeneralizado;
    public javax.swing.JButton btnTrapecioGeneralizado;
    public javax.swing.JButton btnTrapecioSencillo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JMenuItem jSimpson;
    public javax.swing.JMenuItem jTrapecio;
    public javax.swing.JMenuItem jsalir1;
    public javax.swing.JLabel lblTamanoMatriz1;
    public javax.swing.JLabel lblTamanoMatriz2;
    public javax.swing.JLabel lblTamanoMatriz3;
    public javax.swing.JLabel lblTamanoMatriz4;
    public javax.swing.JLabel lblTamanoMatriz5;
    public javax.swing.JTabbedPane panel3;
    public java.awt.TextArea textArea1;
    public javax.swing.JTextField txtDelta;
    public javax.swing.JTextField txtFuncion;
    public javax.swing.JTextField txtLimiteInferior;
    public javax.swing.JTextField txtLimiteSuperior;
    public javax.swing.JTextField txtParticiones;
    // End of variables declaration

}
