package co.edu.eafit.analisisnumerico.GUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JComponent;

import co.edu.eafit.analisisnumerico.framework.Constantes;
import co.edu.eafit.analisisnumerico.framework.GestorAyuda;

public class GUIPrincipalUnidad1 extends javax.swing.JFrame {

    /** Creates new form GUIPrincipal */
    public GUIPrincipalUnidad1() {
        initComponents();
        jTabbedPane1.setVisible(false);
        jLabel13.setVisible(false);
        btnRegresar.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jTabbedPane1.setVisible(true);
                jLabel13.setVisible(true);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFx = new javax.swing.JTextField();
        txtFdev = new javax.swing.JTextField();
        txtG = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnRegresar = new javax.swing.JButton();
        btnAyudas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fnBusquedas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fnBiseccion = new javax.swing.JButton();
        fnReglaFalsa = new javax.swing.JButton();
        fnPuntoFijo = new javax.swing.JButton();
        fnNewton = new javax.swing.JButton();
        fnSecante = new javax.swing.JButton();
        fnRaicesMultiples = new javax.swing.JButton();
        btnMetodos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jsalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jBusquedas = new javax.swing.JMenuItem();
        jBiseccion = new javax.swing.JMenuItem();
        jReglaFalsa = new javax.swing.JMenuItem();
        jPuntoFijo = new javax.swing.JMenuItem();
        jNewton = new javax.swing.JMenuItem();
        jSecante = new javax.swing.JMenuItem();
        jRaices = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        InfoGeneral = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eafit/analisisnumerico/GUI/logo2.JPG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18));
        jLabel2.setText("Análisis Númerico Solver");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel3.setText("Ingreso de funciones");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel4.setText("f(x)");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel5.setText("g(x)");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel6.setText("f'(x)");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel7.setText("f''(x)");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel8.setText("=");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel9.setText("=");

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel10.setText("=");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel11.setText("=");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAyudas.setText("Ayudas");
        btnAyudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel13.setText("Métodos Numéricos");

        fnBusquedas.setFont(new java.awt.Font("Georgia", 0, 11));
        fnBusquedas.setText("Búsquedas incrementales");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(fnBusquedas)
                .addContainerGap(445, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fnBusquedas)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Búsqueda de intervalos", jPanel2);

        fnBiseccion.setFont(new java.awt.Font("Georgia", 0, 11));
        fnBiseccion.setText("Bisección");

        fnReglaFalsa.setFont(new java.awt.Font("Georgia", 0, 11));
        fnReglaFalsa.setText("Regla Falsa");

        fnPuntoFijo.setFont(new java.awt.Font("Georgia", 0, 11));
        fnPuntoFijo.setText("Punto Fijo");

        fnNewton.setFont(new java.awt.Font("Georgia", 0, 11));
        fnNewton.setText("Newton");

        fnSecante.setFont(new java.awt.Font("Georgia", 0, 11));
        fnSecante.setText("Secante");

        fnRaicesMultiples.setFont(new java.awt.Font("Georgia", 0, 11));
        fnRaicesMultiples.setText("Raices Múltiples");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnReglaFalsa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(fnPuntoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(fnBiseccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnRaicesMultiples, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fnSecante, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(fnNewton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(343, 343, 343))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnBiseccion)
                    .addComponent(fnNewton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnReglaFalsa)
                    .addComponent(fnSecante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnPuntoFijo)
                    .addComponent(fnRaicesMultiples))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ecuaciones No Lineales", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
        );

        btnMetodos.setText("Metodos");
        btnMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodosActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jsalir.setText("Salir");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });
        jMenu1.add(jsalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayudas");

        jBusquedas.setText("Busquedas Incrementales");
        jBusquedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBusquedasActionPerformed(evt);
            }
        });
        jMenu2.add(jBusquedas);

        jBiseccion.setText("Biseccion");
        jBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiseccionActionPerformed(evt);
            }
        });
        jMenu2.add(jBiseccion);

        jReglaFalsa.setText("ReglaFalsa");
        jReglaFalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReglaFalsaActionPerformed(evt);
            }
        });
        jMenu2.add(jReglaFalsa);

        jPuntoFijo.setText("Punto Fijo");
        jPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPuntoFijoActionPerformed(evt);
            }
        });
        jMenu2.add(jPuntoFijo);

        jNewton.setText("Newton");
        jNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewtonActionPerformed(evt);
            }
        });
        jMenu2.add(jNewton);

        jSecante.setText("Secante");
        jSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSecanteActionPerformed(evt);
            }
        });
        jMenu2.add(jSecante);

        jRaices.setText("Raices Multiples");
        jRaices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaicesActionPerformed(evt);
            }
        });
        jMenu2.add(jRaices);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Acerca de");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        InfoGeneral.setText("Información General ");
        InfoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoGeneralActionPerformed(evt);
            }
        });
        jMenu3.add(InfoGeneral);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFx, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFdev, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(104, 104, 104)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAyudas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addComponent(btnMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(txtFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(txtFdev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegresar)
                                    .addComponent(btnMetodos))
                                .addGap(18, 18, 18)
                                .addComponent(btnAyudas)))
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

 

 

 

 


     private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAyudasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnMetodosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}
    private void jBiseccionActionPerformed(java.awt.event.ActionEvent evt) {
        GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.BISECCION);
}

    private void jNewtonActionPerformed(java.awt.event.ActionEvent evt) {
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.NEWTON);
    }
     private void jPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {
    	 GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.PUNTOFIJO);
    }
     private void jReglaFalsaActionPerformed(java.awt.event.ActionEvent evt) {
    	 GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.REGLAFALSA);
    }
     private void jRaicesActionPerformed(java.awt.event.ActionEvent evt) {
    	 GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.RAICESMULTIPLES);
    }
    private void jBusquedasActionPerformed(java.awt.event.ActionEvent evt) {
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.BUSQUEDASINCREMENTALES);
    }
    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }
    private void jSecanteActionPerformed(java.awt.event.ActionEvent evt) {
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.SECANTE);
    }

    private void InfoGeneralActionPerformed(java.awt.event.ActionEvent evt) {
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.INFOGENERAL);
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem InfoGeneral;
    private javax.swing.JButton btnAyudas;
    private javax.swing.JButton btnMetodos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton fnBiseccion;
    private javax.swing.JButton fnBusquedas;
    private javax.swing.JButton fnNewton;
    private javax.swing.JButton fnPuntoFijo;
    private javax.swing.JButton fnRaicesMultiples;
    private javax.swing.JButton fnReglaFalsa;
    private javax.swing.JButton fnSecante;
    private javax.swing.JMenuItem jBiseccion;
    private javax.swing.JMenuItem jBusquedas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jNewton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem jPuntoFijo;
    private javax.swing.JMenuItem jRaices;
    private javax.swing.JMenuItem jReglaFalsa;
    private javax.swing.JMenuItem jSecante;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JMenuItem jsalir;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField txtFdev;
    private javax.swing.JTextField txtFx;
    private javax.swing.JTextField txtG;
    // End of variables declaration
    
	/**
	 * @return the btnAyudas
	 */
	public javax.swing.JButton getBtnAyudas() {
		return btnAyudas;
	}

	/**
	 * @param btnAyudas the btnAyudas to set
	 */
	public void setBtnAyudas(javax.swing.JButton btnAyudas) {
		this.btnAyudas = btnAyudas;
	}

	/**
	 * @return the buttonGroup1
	 */
	public javax.swing.ButtonGroup getButtonGroup1() {
		return buttonGroup1;
	}

	/**
	 * @param buttonGroup1 the buttonGroup1 to set
	 */
	public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
		this.buttonGroup1 = buttonGroup1;
	}

	/**
	 * @return the fnBiseccion
	 */
	public javax.swing.JButton getFnBiseccion() {
		return fnBiseccion;
	}

	/**
	 * @param fnBiseccion the fnBiseccion to set
	 */
	public void setFnBiseccion(javax.swing.JButton fnBiseccion) {
		this.fnBiseccion = fnBiseccion;
	}

	/**
	 * @return the fnBusquedas
	 */
	public javax.swing.JButton getFnBusquedas() {
		return fnBusquedas;
	}

	/**
	 * @param fnBusquedas the fnBusquedas to set
	 */
	public void setFnBusquedas(javax.swing.JButton fnBusquedas) {
		this.fnBusquedas = fnBusquedas;
	}

	/**
	 * @return the fnNewton
	 */
	public javax.swing.JButton getFnNewton() {
		return fnNewton;
	}

	/**
	 * @param fnNewton the fnNewton to set
	 */
	public void setFnNewton(javax.swing.JButton fnNewton) {
		this.fnNewton = fnNewton;
	}

	/**
	 * @return the fnPuntoFijo
	 */
	public javax.swing.JButton getFnPuntoFijo() {
		return fnPuntoFijo;
	}

	/**
	 * @param fnPuntoFijo the fnPuntoFijo to set
	 */
	public void setFnPuntoFijo(javax.swing.JButton fnPuntoFijo) {
		this.fnPuntoFijo = fnPuntoFijo;
	}

	/**
	 * @return the fnRaicesMultiples
	 */
	public javax.swing.JButton getFnRaicesMultiples() {
		return fnRaicesMultiples;
	}

	/**
	 * @param fnRaicesMultiples the fnRaicesMultiples to set
	 */
	public void setFnRaicesMultiples(javax.swing.JButton fnRaicesMultiples) {
		this.fnRaicesMultiples = fnRaicesMultiples;
	}

	/**
	 * @return the fnReglaFalsa
	 */
	public javax.swing.JButton getFnReglaFalsa() {
		return fnReglaFalsa;
	}

	/**
	 * @param fnReglaFalsa the fnReglaFalsa to set
	 */
	public void setFnReglaFalsa(javax.swing.JButton fnReglaFalsa) {
		this.fnReglaFalsa = fnReglaFalsa;
	}

	/**
	 * @return the fnSecante
	 */
	public javax.swing.JButton getFnSecante() {
		return fnSecante;
	}

	/**
	 * @param fnSecante the fnSecante to set
	 */
	public void setFnSecante(javax.swing.JButton fnSecante) {
		this.fnSecante = fnSecante;
	}

	/**
	 * @return the jPanel1
	 */
	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}

	/**
	 * @param jPanel1 the jPanel1 to set
	 */
	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	/**
	 * @return the jPanel2
	 */
	public javax.swing.JPanel getjPanel2() {
		return jPanel2;
	}

	/**
	 * @param jPanel2 the jPanel2 to set
	 */
	public void setjPanel2(javax.swing.JPanel jPanel2) {
		this.jPanel2 = jPanel2;
	}

	/**
	 * @return the jPanel3
	 */
	public javax.swing.JPanel getjPanel3() {
		return jPanel3;
	}

	/**
	 * @param jPanel3 the jPanel3 to set
	 */
	public void setjPanel3(javax.swing.JPanel jPanel3) {
		this.jPanel3 = jPanel3;
	}

	/**
	 * @return the jSeparator1
	 */
	public javax.swing.JSeparator getjSeparator1() {
		return jSeparator1;
	}

	/**
	 * @param jSeparator1 the jSeparator1 to set
	 */
	public void setjSeparator1(javax.swing.JSeparator jSeparator1) {
		this.jSeparator1 = jSeparator1;
	}

	/**
	 * @return the jSeparator2
	 */
	public javax.swing.JSeparator getjSeparator2() {
		return jSeparator2;
	}

	/**
	 * @param jSeparator2 the jSeparator2 to set
	 */
	public void setjSeparator2(javax.swing.JSeparator jSeparator2) {
		this.jSeparator2 = jSeparator2;
	}

	/**
	 * @return the jSeparator3
	 */
	public javax.swing.JSeparator getjSeparator3() {
		return jSeparator3;
	}

	/**
	 * @param jSeparator3 the jSeparator3 to set
	 */
	public void setjSeparator3(javax.swing.JSeparator jSeparator3) {
		this.jSeparator3 = jSeparator3;
	}

	/**
	 * @return the jTabbedPane1
	 */
	public javax.swing.JTabbedPane getjTabbedPane1() {
		return jTabbedPane1;
	}

	/**
	 * @param jTabbedPane1 the jTabbedPane1 to set
	 */
	public void setjTabbedPane1(javax.swing.JTabbedPane jTabbedPane1) {
		this.jTabbedPane1 = jTabbedPane1;
	}

	/**
	 * @return the jTextField4
	 */
/*	public javax.swing.JTextField getFdd() {
		return txtFdd;
	}
	public void setFdd(javax.swing.JTextField jTextField4) {
		this.txtFdd = jTextField4;
	}*/

	/**
	 * @return the txtFdev
	 */
	public javax.swing.JTextField getTxtFdev() {
		return txtFdev;
	}

	/**
	 * @param txtFdev the txtFdev to set
	 */
	public void setTxtFdev(javax.swing.JTextField txtFdev) {
		this.txtFdev = txtFdev;
	}

	/**
	 * @return the txtFx
	 */
	public javax.swing.JTextField getTxtFx() {
		return txtFx;
	}

	/**
	 * @param txtFx the txtFx to set
	 */
	public void setTxtFx(javax.swing.JTextField txtFx) {
		this.txtFx = txtFx;
	}

	/**
	 * @return the txtG
	 */
	public javax.swing.JTextField getTxtG() {
		return txtG;
	}

	/**
	 * @param txtG the txtG to set
	 */
	public void setTxtG(javax.swing.JTextField txtG) {
		this.txtG = txtG;
	}

	public JComponent getjLabel13() {
		return jLabel13;
	}

	/**
	 * @return the btnMetodos
	 */
	public javax.swing.JButton getBtnMetodos() {
		return btnMetodos;
	}

}
