package co.edu.eafit.analisisnumerico.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.table.DefaultTableModel;

import co.edu.eafit.analisisnumerico.framework.AnalisisException;
import co.edu.eafit.analisisnumerico.framework.Constantes;
import co.edu.eafit.analisisnumerico.framework.GestorInterfazPrincipalSistemasEcuaciones;
import co.edu.eafit.analisisnumerico.framework.GestorMetodos;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PopUpMISistemasEcuaciones.java
 *
 * Created on 1/05/2010, 03:42:45 PM
 */


/**
 *
 * @author nico
 */
public class PopUpRelajacion extends javax.swing.JFrame {

	GestorInterfazPrincipalSistemasEcuaciones gestor;
	int metodo;
	int tamano;
	
	/** Creates new form PopUpMISistemasEcuaciones */
    public PopUpRelajacion(final GestorInterfazPrincipalSistemasEcuaciones gestor, final int metodo, final Object[][] matriz) {
    	this.gestor=gestor;
    	this.metodo=metodo;
        initComponents();
        setVisible(true);
        tamano=matriz.length;
        Object[][] datos = new Object[1][matriz.length];
        String[] titulos = new String[matriz.length];
        for(int i=0;i<matriz.length;i++)titulos[i]="X"+(i+1);
        tblValoresIniciales.setModel(new DefaultTableModel(datos, titulos));
        btnRegresar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				PopUpRelajacion.this.setVisible(false);
			}
		});
        btnAceptar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				double[] valoresObtenidos = generarValoresObtenidos();
				if(valoresObtenidos==null)return;
				GestorMetodos.ejecutarSistemaEcuacion(Constantes.RELAJACION, "Relajacion", matriz, valoresObtenidos);

			}
		});
    }
    
    protected double[] generarValoresObtenidos() {
    	double[] resul = new double[tamano+3];
    	try{
    		//POSICION 0-> TOLERANCIA
    		resul[0] = Double.parseDouble(txtTol.getText());
    		resul[1] = Double.parseDouble(txtIter.getText());
    		resul[2] = Double.parseDouble(txtLambda.getText());
    		for(int i=0;i<tamano;i++){
    			resul[i+2]=Double.parseDouble(tblValoresIniciales.getValueAt(0, i).toString());
    		}
    		return resul;
    	}
    	catch(Exception e){
    		new AnalisisException("ENTRADA INVALIDA");
    		return null;
    	}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtLambda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblValoresIniciales = new javax.swing.JTable();
        txtIter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eafit/analisisnumerico/GUI/logo2.JPG"))); // NOI18N

        jLabel2.setText("Ingrese Lambda");

        btnAceptar.setText("Aceptar");

        btnRegresar.setText("Regresar");

        txtLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLambdaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese Valores Iniciales");

        tblValoresIniciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Valores"
            }
        ));
        jScrollPane1.setViewportView(tblValoresIniciales);

        txtIter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIterActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese numero de Iteraciones");

        txtTol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTolActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrese Tolerancia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(89, 89, 89)
                                            .addComponent(txtLambda)
                                            .addGap(108, 108, 108))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAceptar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRegresar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtIter, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(77, 77, 77)
                                .addComponent(txtTol, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnRegresar))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>

    private void txtLambdaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
}                                      

    private void txtIterActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    private void txtTolActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}


    // Variables declaration - do not modify
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblValoresIniciales;
    private javax.swing.JTextField txtIter;
    private javax.swing.JTextField txtLambda;
    private javax.swing.JTextField txtTol;
    // End of variables declaration

}
