/*
 * To change this template, choose Tools | Templates

 * and open the template in the editor.
 */

/*
 * SistemasEcuacionesGUI.java
 *
 * Created on 17/04/2010, 03:21:23 PM
 */

package co.edu.eafit.analisisnumerico.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.table.DefaultTableModel;

import co.edu.eafit.analisisnumerico.framework.Constantes;
import co.edu.eafit.analisisnumerico.framework.GestorAyuda;
import co.edu.eafit.analisisnumerico.framework.GestorInterfazPrincipalSistemasEcuaciones;

/**
 *
 * @author nico
 */
public class SistemasEcuacionesGUI extends javax.swing.JFrame {

	/*setea el tamano de la matriz*/
	int tamano;
	
    /** Creates new form SistemasEcuacionesGUI */
    public SistemasEcuacionesGUI() {
        initComponents();
        setResizable(false);
this.txtTamanoMatriz.addKeyListener(new KeyListener() {
			
			@Override
			public void keyTyped(KeyEvent arg0) {
				//MetodoGUI2.this.crearTabla();
				
			}
			
			@Override
			public void keyReleased(KeyEvent arg0) {
				SistemasEcuacionesGUI.this.crearTabla();
			}
			
			@Override
			public void keyPressed(KeyEvent arg0) {
				//MetodoGUI2.this.crearTabla();	
			}
		});
    }
    
    /*METODOS PROPIOS DE LA LOGICA DEL NEGOCIO*/
    protected void crearTabla() {
    	try{
    		tamano = Integer.parseInt(txtTamanoMatriz.getText().trim());
    		if(tamano>30)return;
    	}
		catch(Exception e){
			tamano=4;
			Object[] titulos = new Object[tamano+1];
			for(int i=0;i<tamano+1;i++){
				if(i==tamano){
					titulos[i] = "B";
				}
				else{
					titulos[i] = new String("X"+(i+1));
				}
				
			}
			Object[][] datos = {{"20","-1","1","-1","8"},{"5","35","-4","8","50"},{"2","-10","75","-1","-114"},{"3","-7","4","-27","10"}};
			
			tablaMatriz.setModel(new DefaultTableModel(datos, titulos));
			return;
		}
		Object[] titulos = new Object[tamano+1];
		for(int i=0;i<tamano+1;i++){
			if(i==tamano){
				titulos[i] = "B";
			}
			else{
				titulos[i] = new String("X"+(i+1));
			}
			
		}
		Object[][] datos = new Object[tamano][tamano+1];
		for(int i=0;i<datos.length;i++){
			for(int j=0;j<datos.length;j++){
				datos[i][j] = new String("");
			}
		}

		tablaMatriz.setModel(new DefaultTableModel(datos, titulos));
	}

    public Object[][] getTabla(){
    	Object[][] resul = new Object[tamano][tamano+1];
    	for(int i=0;i<tamano;i++){
    		for(int j=0;j<tamano+1;j++){
    			try{
    				resul[i][j] = tablaMatriz.getValueAt(i, j).toString();
    			}
    			catch(Exception e){
    				System.out.println(i+","+j);
    			}
    			
    		}
    	}
    	return resul;
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMatriz = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        
        btnAyuda = new javax.swing.JButton();
        lblTamanoMatriz = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtTamanoMatriz = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnEliminacionGauss = new javax.swing.JButton();
        btnPivoteoParcial = new javax.swing.JButton();
        btnPivoteoTotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLUGaussianaSimple = new javax.swing.JButton();
        btnLUGaussianaParcial = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCholesky = new javax.swing.JButton();
        btnCroult = new javax.swing.JButton();
        btnDolytle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnJacobi = new javax.swing.JButton();
        btnGaussSeidel = new javax.swing.JButton();
        btnRelajacion = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnMatrizBanda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jsalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jeliminacion = new javax.swing.JMenuItem();
        jpivoteoparcial = new javax.swing.JMenuItem();
        jpivoteototal = new javax.swing.JMenuItem();
        jgaussianaSimple = new javax.swing.JMenuItem();
        jgaussianaParcial = new javax.swing.JMenuItem();
        jcholesky = new javax.swing.JMenuItem();
        jcroult = new javax.swing.JMenuItem();
        jdolytle = new javax.swing.JMenuItem();
        jjacobi = new javax.swing.JMenuItem();
        jgausseidel = new javax.swing.JMenuItem();
        jrealajacion = new javax.swing.JMenuItem();
        jmatrizbanda = new javax.swing.JMenuItem();
        
        jMenu3 = new javax.swing.JMenu();
        InfoGeneral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablaMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingrese por favor el tamaño de la matriz y presione Enter"
            }
        ));
        jScrollPane1.setViewportView(tablaMatriz);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("Análisis Numérico Solver");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eafit/analisisnumerico/GUI/logo2.JPG"))); // NOI18N

        btnRegresar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnRegresar.setText("Regresar");
        
        btnAyuda.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnAyuda.setText("Ayuda");

        lblTamanoMatriz.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lblTamanoMatriz.setText("Tamaño de la matriz");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14));
        jLabel13.setText("Métodos Numéricos");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnEliminacionGauss.setFont(new java.awt.Font("Georgia", 0, 11));
        btnEliminacionGauss.setText("Eliminación Gaussiana");

        btnPivoteoParcial.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnPivoteoParcial.setText("Pivoteo Parcial");
        btnPivoteoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPivoteoParcialActionPerformed(evt);
            }
        });

        btnPivoteoTotal.setFont(new java.awt.Font("Georgia", 0, 11));
        btnPivoteoTotal.setText("Pivoteo Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPivoteoTotal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPivoteoParcial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEliminacionGauss)
                        .addGap(183, 183, 183)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminacionGauss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPivoteoParcial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPivoteoTotal)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        panel.addTab("Eliminación Gaussiana", jPanel2);

        btnLUGaussianaSimple.setFont(new java.awt.Font("Georgia", 0, 11));
        btnLUGaussianaSimple.setText("LU Gaussiana Simple");

        btnLUGaussianaParcial.setFont(new java.awt.Font("Georgia", 0, 11));
        btnLUGaussianaParcial.setText("LU Gaussiana Parcial");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLUGaussianaParcial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(594, 594, 594))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLUGaussianaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(464, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLUGaussianaSimple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLUGaussianaParcial)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        panel.addTab("LU Eliminación Gaussiana", jPanel3);

        btnCholesky.setFont(new java.awt.Font("Georgia", 0, 11));
        btnCholesky.setText("Cholesky Lii=Uii");

        btnCroult.setFont(new java.awt.Font("Georgia", 0, 11));
        btnCroult.setText("Croult Uii=1");

        btnDolytle.setFont(new java.awt.Font("Georgia", 0, 11));
        btnDolytle.setText("Dolytle Lii=1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCholesky)
                    .addComponent(btnCroult)
                    .addComponent(btnDolytle))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCholesky)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCroult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDolytle)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        panel.addTab("Factorización Directa de Matrices", jPanel4);

        btnJacobi.setFont(new java.awt.Font("Georgia", 0, 11));
        btnJacobi.setText("Jacobi");

        btnGaussSeidel.setFont(new java.awt.Font("Georgia", 0, 11));
        btnGaussSeidel.setText("Gauss Seidel");

        btnRelajacion.setFont(new java.awt.Font("Georgia", 0, 11));
        btnRelajacion.setText("Relajación (SOR)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJacobi)
                    .addComponent(btnGaussSeidel)
                    .addComponent(btnRelajacion))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnJacobi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGaussSeidel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRelajacion)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panel.addTab("Métodos Iterativos", jPanel5);

        btnMatrizBanda.setFont(new java.awt.Font("Georgia", 0, 11));
        btnMatrizBanda.setText("Matriz Banda");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMatrizBanda)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMatrizBanda)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        panel.addTab("Tipo Especial de Matrices", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
        );

        jMenu1.setText("Archivo");

        jsalir.setText("Salir");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });
        jMenu1.add(jsalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayudas");

        jeliminacion.setText("Eliminación Gaussiana");
        jeliminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeliminacionActionPerformed(evt);
            }
        });
        jMenu2.add(jeliminacion);

        jpivoteoparcial.setText("Pivoteo Parcial");
        jpivoteoparcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpivoteoparcialActionPerformed(evt);
            }
        });
        jMenu2.add(jpivoteoparcial);

        jpivoteototal.setText("Pivoteo Total");
        jpivoteototal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpivoteototalActionPerformed(evt);
            }
        });
        jMenu2.add(jpivoteototal);

        jgaussianaSimple.setText("LU Gaussiana Simple");
        jgaussianaSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgaussianaSimpleActionPerformed(evt);
            }
        });
        jMenu2.add(jgaussianaSimple);

        jgaussianaParcial.setText("LU Gaussiana Parcial");
        jgaussianaParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgaussianaParcialActionPerformed(evt);
            }
        });
        jMenu2.add(jgaussianaParcial);

        jcholesky.setText("Cholesky");
        jcholesky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcholeskyActionPerformed(evt);
            }
        });
        jMenu2.add(jcholesky);

        jcroult.setText("Croult");
        jcroult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcroultActionPerformed(evt);
            }
        });
        jMenu2.add(jcroult);

        jdolytle.setText("Dolytle");
        jdolytle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdolytleActionPerformed(evt);
            }
        });
        jMenu2.add(jdolytle);

        jjacobi.setText("Jacobi");
        jjacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjacobiActionPerformed(evt);
            }
        });
        jMenu2.add(jjacobi);

        jgausseidel.setText("Gauss Seidel");
        jgausseidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgausseidelActionPerformed(evt);
            }
        });
        jMenu2.add(jgausseidel);

        jrealajacion.setText("Relajación");
        jrealajacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrealajacionActionPerformed(evt);
            }
        });
        jMenu2.add(jrealajacion);

        jmatrizbanda.setText("Matriz Banda");
        jmatrizbanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmatrizbandaActionPerformed(evt);
            }
        });
        jMenu2.add(jmatrizbanda);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Acerca de");

        InfoGeneral.setText("Información General ");
        InfoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoGeneralActionPerformed(evt);
            }
        });
        jMenu3.add(InfoGeneral);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTamanoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTamanoMatriz)
                                    .addComponent(jSeparator4)))
                                .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnAyuda,javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnRegresar,javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(140, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(708, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                            	.addGap(169, 169, 169)
                                .addComponent(btnAyuda)
                                .addGap(20, 20, 20)
                                .addComponent(btnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTamanoMatriz)
                                .addGap(11, 11, 11)
                                .addComponent(txtTamanoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(598, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPivoteoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPivoteoParcialActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnPivoteoParcialActionPerformed

    private void jeliminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeliminacionActionPerformed
        GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.GAUSSSIMPLE);
}//GEN-LAST:event_jeliminacionActionPerformed

    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jsalirActionPerformed


    private void jpivoteoparcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpivoteoparcialActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.PIVOTEOPARCIAL);
    }//GEN-LAST:event_jpivoteoparcialActionPerformed

    private void jpivoteototalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpivoteototalActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.PIVOTEOTOTAL);
    }//GEN-LAST:event_jpivoteototalActionPerformed

    private void jgaussianaSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgaussianaSimpleActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.LUSIMPLE);
    }//GEN-LAST:event_jgaussianaSimpleActionPerformed

    private void jgaussianaParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgaussianaParcialActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.LUPIVOTEO);
    }//GEN-LAST:event_jgaussianaParcialActionPerformed

    private void jcholeskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcholeskyActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.CHOLESKY);
    }//GEN-LAST:event_jcholeskyActionPerformed

    private void jcroultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcroultActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.CROULT);
    }//GEN-LAST:event_jcroultActionPerformed

    private void jdolytleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdolytleActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.DOOLITTLE);
    }//GEN-LAST:event_jdolytleActionPerformed

    private void jjacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjacobiActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.JACOBI);
    }//GEN-LAST:event_jjacobiActionPerformed

    private void jgausseidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgausseidelActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.GAUSSSEIDEL);
    }//GEN-LAST:event_jgausseidelActionPerformed

    private void jrealajacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrealajacionActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.RELAJACION);
    }//GEN-LAST:event_jrealajacionActionPerformed

    private void jmatrizbandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmatrizbandaActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.MATRIZBANDA);
    }//GEN-LAST:event_jmatrizbandaActionPerformed

    private void InfoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoGeneralActionPerformed
    	GestorAyuda.getInstance().mostrarAyudaMetodo(Constantes.INFOGENERAL);
}//GEN-LAST:event_InfoGeneralActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemasEcuacionesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InfoGeneral;
    private javax.swing.JButton btnCholesky;
    private javax.swing.JButton btnCroult;
    private javax.swing.JButton btnDolytle;
    private javax.swing.JButton btnEliminacionGauss;
    private javax.swing.JButton btnGaussSeidel;
    private javax.swing.JButton btnJacobi;
    private javax.swing.JButton btnLUGaussianaParcial;
    private javax.swing.JButton btnLUGaussianaSimple;
    private javax.swing.JButton btnMatrizBanda;
    private javax.swing.JButton btnPivoteoParcial;
    private javax.swing.JButton btnPivoteoTotal;
    private javax.swing.JButton btnRegresar;
    
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnRelajacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuItem jcholesky;
    private javax.swing.JMenuItem jcroult;
    private javax.swing.JMenuItem jdolytle;
    private javax.swing.JMenuItem jeliminacion;
    private javax.swing.JMenuItem jgausseidel;
    private javax.swing.JMenuItem jgaussianaParcial;
    private javax.swing.JMenuItem jgaussianaSimple;
    private javax.swing.JMenuItem jjacobi;
    private javax.swing.JMenuItem jmatrizbanda;
    private javax.swing.JMenuItem jpivoteoparcial;
    private javax.swing.JMenuItem jpivoteototal;
    private javax.swing.JMenuItem jrealajacion;
    private javax.swing.JMenuItem jsalir;
    private javax.swing.JLabel lblTamanoMatriz;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JTable tablaMatriz;
    private javax.swing.JTextField txtTamanoMatriz;
    // End of variables declaration//GEN-END:variables

    //GETS Y SETYS PARA SETEAR EVENTOS
    
	/**
	 * @return the btnCholesky
	 */
	public javax.swing.JButton getBtnCholesky() {
		return btnCholesky;
	}

	/**
	 * @param btnCholesky the btnCholesky to set
	 */
	public void setBtnCholesky(javax.swing.JButton btnCholesky) {
		this.btnCholesky = btnCholesky;
	}

	/**
	 * @return the btnCroult
	 */
	public javax.swing.JButton getBtnCroult() {
		return btnCroult;
	}

	/**
	 * @param btnCroult the btnCroult to set
	 */
	public void setBtnCroult(javax.swing.JButton btnCroult) {
		this.btnCroult = btnCroult;
	}

	/**
	 * @return the btnDolytle
	 */
	public javax.swing.JButton getBtnDolytle() {
		return btnDolytle;
	}

	/**
	 * @param btnDolytle the btnDolytle to set
	 */
	public void setBtnDolytle(javax.swing.JButton btnDolytle) {
		this.btnDolytle = btnDolytle;
	}

	/**
	 * @return the btnEliminacionGauss
	 */
	public javax.swing.JButton getBtnEliminacionGauss() {
		return btnEliminacionGauss;
	}

	/**
	 * @param btnEliminacionGauss the btnEliminacionGauss to set
	 */
	public void setBtnEliminacionGauss(javax.swing.JButton btnEliminacionGauss) {
		this.btnEliminacionGauss = btnEliminacionGauss;
	}

	/**
	 * @return the btnGaussSeidel
	 */
	public javax.swing.JButton getBtnGaussSeidel() {
		return btnGaussSeidel;
	}

	/**
	 * @param btnGaussSeidel the btnGaussSeidel to set
	 */
	public void setBtnGaussSeidel(javax.swing.JButton btnGaussSeidel) {
		this.btnGaussSeidel = btnGaussSeidel;
	}

	/**
	 * @return the btnJacobi
	 */
	public javax.swing.JButton getBtnJacobi() {
		return btnJacobi;
	}

	/**
	 * @param btnJacobi the btnJacobi to set
	 */
	public void setBtnJacobi(javax.swing.JButton btnJacobi) {
		this.btnJacobi = btnJacobi;
	}

	/**
	 * @return the btnLUGaussianaParcial
	 */
	public javax.swing.JButton getBtnLUGaussianaParcial() {
		return btnLUGaussianaParcial;
	}

	/**
	 * @param btnLUGaussianaParcial the btnLUGaussianaParcial to set
	 */
	public void setBtnLUGaussianaParcial(javax.swing.JButton btnLUGaussianaParcial) {
		this.btnLUGaussianaParcial = btnLUGaussianaParcial;
	}

	/**
	 * @return the btnLUGaussianaSimple
	 */
	public javax.swing.JButton getBtnLUGaussianaSimple() {
		return btnLUGaussianaSimple;
	}

	/**
	 * @param btnLUGaussianaSimple the btnLUGaussianaSimple to set
	 */
	public void setBtnLUGaussianaSimple(javax.swing.JButton btnLUGaussianaSimple) {
		this.btnLUGaussianaSimple = btnLUGaussianaSimple;
	}

	/**
	 * @return the btnMatrizBanda
	 */
	public javax.swing.JButton getBtnMatrizBanda() {
		return btnMatrizBanda;
	}

	/**
	 * @param btnMatrizBanda the btnMatrizBanda to set
	 */
	public void setBtnMatrizBanda(javax.swing.JButton btnMatrizBanda) {
		this.btnMatrizBanda = btnMatrizBanda;
	}

	/**
	 * @return the btnPivoteoParcial
	 */
	public javax.swing.JButton getBtnPivoteoParcial() {
		return btnPivoteoParcial;
	}

	/**
	 * @param btnPivoteoParcial the btnPivoteoParcial to set
	 */
	public void setBtnPivoteoParcial(javax.swing.JButton btnPivoteoParcial) {
		this.btnPivoteoParcial = btnPivoteoParcial;
	}

	/**
	 * @return the btnPivoteoTotal
	 */
	public javax.swing.JButton getBtnPivoteoTotal() {
		return btnPivoteoTotal;
	}

	/**
	 * @param btnPivoteoTotal the btnPivoteoTotal to set
	 */
	public void setBtnPivoteoTotal(javax.swing.JButton btnPivoteoTotal) {
		this.btnPivoteoTotal = btnPivoteoTotal;
	}

	/**
	 * @return the btnRegresar
	 */
	public javax.swing.JButton getBtnRegresar() {
		return btnRegresar;
	}

	/**
	 * @param btnRegresar the btnRegresar to set
	 */
	public void setBtnRegresar(javax.swing.JButton btnRegresar) {
		this.btnRegresar = btnRegresar;
	}

	/**
	 * @return the btnRelajacion
	 */
	public javax.swing.JButton getBtnRelajacion() {
		return btnRelajacion;
	}

	/**
	 * @param btnRelajacion the btnRelajacion to set
	 */
	public void setBtnRelajacion(javax.swing.JButton btnRelajacion) {
		this.btnRelajacion = btnRelajacion;
	}

    

    
    
    
}
